version: '3'

services:
  nginx:
    ports:
      - 17780:80
    networks:
      app_net: 
        ipv4_address: 172.16.1.2

  php:
    networks:
      app_net: 
        ipv4_address: 172.16.1.4

  mariadb:
    ports:
      - 17706:3306
    networks:
      app_net: 
        ipv4_address: 172.16.1.8

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/28

